# Generated by Django 2.2.4 on 2019-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
