# Generated by Django 2.2.4 on 2019-08-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hikr_app', '0003_auto_20190812_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
