# Generated by Django 2.2.4 on 2019-08-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikr_app', '0004_like_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_profile', to='hikr_app.Profile'),
            preserve_default=False,
        ),
    ]
